language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 2FRcu4FQafEX7Case99Li9cd0Yb/hPYNdsiqaqMoI8ty5oNN011JRKM4gQgNH4oXJWkQiVjElU9NY9LSSiWer1q5YAhTnRlKuYM1B3TSpn1+QvcXJoEWrGYcu3EZnuJhiF5/Zvn7Uaiu8J5WBxqL8Wh24ffVkogSHVEDxytxrc5Idzk4/BNWdgDPUJuSUlDaj8zWTvoO8E7sJEqTzI7mSeRcc8K3alYidamK2icb01gL+DmnKVs+4NAWkW1mcAgoXfqrK6fE9PVhwJcP3cdPBI7fTKzckysNJuv6GiPkJfq5uR7kiRYW3wRiWMcou7N/8tL26qHe3rxOFNKEpiKXlvlWJYr4bzyVKREvJ57yfZYY07oBJufOLVDrKGOY/qfzQpY9b7s6dvbMrVh2XGppJPq27vnEiDWzfDR3/Yb8mxlkWPdbzbL0y2+q0PxdIJJENE2B/jBYOcsGlz4SRCeKuxQe6jzvpsNva4qnUk+6BQHSVM0Xv567Hidt7VsRpxVQeS3UsXb/VEU6ufBR4wJVaXP5/tXB3vo5GThlBe+QqVRM1OjHwkh7SkElsZ8yB3GbVFEuf6hIj1dAeE6k5XZDZmEWNOSR8O00rjTM41ysUEOZl28+ifXDRcQwELL0qaTHB2BnbtpiO7gWCqIXXF0J0FoWAv5H47KHRp1LnSRicZ8=
  app: fstopandgo-api
  on:
    repo: AlexWarnes/fStopandGo-api
