language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 2FRcu4FQafEX7Case99Li9cd0Yb/hPYNdsiqaqMoI8ty5oNN011JRKM4gQgNH4oXJWkQiVjElU9NY9LSSiWer1q5YAhTnRlKuYM1B3TSpn1+QvcXJoEWrGYcu3EZnuJhiF5/Zvn7Uaiu8J5WBxqL8Wh24ffVkogSHVEDxytxrc5Idzk4/BNWdgDPUJuSUlDaj8zWTvoO8E7sJEqTzI7mSeRcc8K3alYidamK2icb01gL+DmnKVs+4NAWkW1mcAgoXfqrK6fE9PVhwJcP3cdPBI7fTKzckysNJuv6GiPkJfq5uR7kiRYW3wRiWMcou7N/8tL26qHe3rxOFNKEpiKXlvlWJYr4bzyVKREvJ57yfZYY07oBJufOLVDrKGOY/qfzQpY9b7s6dvbMrVh2XGppJPq27vnEiDWzfDR3/Yb8mxlkWPdbzbL0y2+q0PxdIJJENE2B/jBYOcsGlz4SRCeKuxQe6jzvpsNva4qnUk+6BQHSVM0Xv567Hidt7VsRpxVQeS3UsXb/VEU6ufBR4wJVaXP5/tXB3vo5GThlBe+QqVRM1OjHwkh7SkElsZ8yB3GbVFEuf6hIj1dAeE6k5XZDZmEWNOSR8O00rjTM41ysUEOZl28+ifXDRcQwELL0qaTHB2BnbtpiO7gWCqIXXF0J0FoWAv5H47KHRp1LnSRicZ8=
  app: fstopandgo-api
  on:
    repo: AlexWarnes/fStopandGo-api
env:
  global:
    secure: BAK2j+F5LLJXq+BIrS3l1YEOfUl5jZD0nOpKYFXlLBI1VFw9EORm/E6WAVWQYYv7ZR+0iyXyy7n8Bq5oHlfVZVsImBw3k8ui/jG6TrENNnNRdHdFp/HxNAWdKpQ/cW0xoehbvZlHeXEyL6dfleamLNhepKS5hWlJCwtyXXVGJuZZDf6uMRBMHJlTuah0WnPu3PuZsu2Dow12VmCEnNnRF6K3Lt0jUHKVuwoyaNunrolHhcqJoc8PbBduo+r/go2S6K9Fi8lsaBt53X0UlZ5P8Bq0xeyzvulERlDZzA6rBB/1Cm2nqhGsC7LkS/S1ei7TCQLw4tV0Egllmqc9nbcSrdXMBbvDCxAaY2Sg7j3ps1J5CUXB8j4cR8QLuZzAjbMYjbdrIqtVh8Bs85A9wvdr+/0qs35Z+pyJV66OjuC6IqTIZ4hVNIdMq2BIacGv+etPjmapDa/7px8/biax/NKINxbAy1nlek6nObWW+zDH18Z/AjlQ1U2p2l5gGd/18Cb7V0zBjQP2C4wvtXjQMBYgFQ5nbpxXytbqeckoxi2QHWPbFIz3gR1BfXtWTxGny3vYTuLgZY5ju424U1+5PGBc7z0dzCxs3W8mCrEzwOtGemX1uX2qXryzqSH7uvtiHrTXR5xH/WJWmpniUzcoOs7QSWDzMuknh6WFQ+ddTAjfbZ4=
